CREATE TABLE HistoricoAtivoIntangivel (
    id SERIAL PRIMARY KEY,
    id_ativo_Intangivel INT,
    nome VARCHAR(100),
    marca VARCHAR(100),
    custo_aquisicao NUMERIC(2),
    data_aquisicao DATE,
    data_cadastro DATE,
    data_expiracao DATE,
    numero_identificacao INT,
    tipo VARCHAR(50),
    tag VARCHAR(50),
    grau_importancia INT,
    status VARCHAR(50),
    ultima_atualizacao DATE,
    id_responsavel INT,
    descricao VARCHAR(500),
    id_nota_fiscal INT,
    FOREIGN KEY (id_ativo_Intangivel) REFERENCES AtivoIntangivel(id_ativo),
    FOREIGN KEY (id_responsavel) REFERENCES Usuario(id),
    FOREIGN KEY (id_nota_fiscal) REFERENCES NotaFiscal(id)
);