CREATE TABLE historicoativointangivel (
    id BIGSERIAL,
    id_ativo_intangivel BIGINT,
    data_expiracao_ativo_intangivel DATE,
    taxa_amortizacao_ativo_intangivel NUMERIC(10, 2),
    periodo_amortizacao_ativo_intangivel VARCHAR(30),
    nome_ativo VARCHAR(100),
    custo_aquisicao_ativo NUMERIC(10, 2),
    tipo_ativo VARCHAR(20),
    tag_ativo VARCHAR(20),
    grau_importancia_ativo BIGINT,
    status_ativo VARCHAR(50),
    descricao_ativo VARCHAR(500),
    numero_identificacao_ativo VARCHAR(50),
    ultima_atualizacao_ativo DATE,
    marca_ativo VARCHAR(100),
    data_aquisicao_ativo DATE,
    campos_personalizados_ativo TEXT,
    nome_usuario VARCHAR(100),
    cpf_usuario VARCHAR(11),
    nascimento_usuario DATE,
    departamento_usuario VARCHAR(20),
    telefone_usuario VARCHAR(20),
    email_usuario VARCHAR(100),
    status_usuario VARCHAR(100),
    id_ativo BIGINT,
    id_usuario BIGINT,
    id_nota_fiscal BIGINT,
    documento_nota_fiscal BYTEA,
    tipo_documento_nota_fiscal VARCHAR(30),
    data_cadastro_ativo DATE,
    valor_residual NUMERIC,
    CONSTRAINT historicoativointangivel_pkey PRIMARY KEY (id)
);
