create table HistoricoAtivoTangivel (
    id int primary key not null auto_increment,
    id_ativo_tangivel int not null,
    data_inicio date,
    data_fim date,
    nome varchar(100),
    marca varchar(100),
    custo_aquisicao int,
    garantia date,
    data_aquisicao date,
    numero_identificador varchar(50),
    ultima_atualizacao date,
    tipo varchar(50),
    tag varchar(50),
    grau_importancia int,
    status varchar(50),
    id_responsavel int,
    descricao varchar(500),
    id_nota_fiscal int,
    foreign key (id_ativo_tangivel) references AtivoTangivel(id),
    foreign key (id_responsavel) references Usuario(id),
    foreign key (id_nota_fiscal) references NotaFiscal(id)
)