CREATE TABLE manutencao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_ativo BIGINT,
    data_inicio DATE,
    data_fim DATE,
    custo NUMERIC,
    tipo INTEGER,
    descricao VARCHAR(200),
    localizacao VARCHAR(100),
    id_nota_fiscal BIGINT,
    CONSTRAINT manutencao_pkey PRIMARY KEY (id),
    CONSTRAINT manutencao_id_ativo_fkey FOREIGN KEY (id_ativo) REFERENCES ativo (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT manutencao_id_nota_fiscal_fkey FOREIGN KEY (id_nota_fiscal) REFERENCES notafiscal (id) ON UPDATE CASCADE ON DELETE SET NULL
);
